config/routes.rb
Rails.application.routes.draw do

  root 'page#travelnote'

  resources :letters

  
  get '/letter' => 'page#letter' ,:as=>'letterlist'
  get '/music' => 'page#music'
  get '/video' => 'page#video'
  get '/book' => 'page#book'
  get '/digest' => 'page#digest'
  get '/image' => 'page#image'
  get '/about' => 'page#about'

  get 'signup' => 'users#signup' , :as => 'signup'
  get 'login' => 'users#login' , :as => 'login'
  post '/create_login_session' => 'users#create_login_session'
  delete 'logout' => 'users#logout' , :as => "logout"

  resources :users , only: [:create]
  resources :issues
  
  

  
   get '/songs/:id' => "songs#show", :as => "song"
   
  post '/issues/:issue_id/comments' => 'comments#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :issue
	belongs_to :song
	def user_avatar
		gravatar_id  = Digest::MD5.hexdigest(self.email.downcase)
		"http://gravatar.com/avatar/#{gravatar_id}.png?s=512&d=retro"
	end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
	has_many :comments
end 

app/models/letter.rb
class Letter < ActiveRecord::Base

end

app/models/song.rb
class Song < ActiveRecord::Base
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	 has_secure_password
	 before_create { generate_token(:auth_token)}
	 def generate_token(column)
	 	begin
	 		
	 	self[column] = SecureRandom.urlsafe_base64
	 	end while User.exists?(column => self[column])
	 end

	 validates :name ,:email,presence: true
	 validates :name ,:email,uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find_by_auth_token!(cookies[:auth_token])if cookies[:auth_token]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		c = Comment.new 
		c.username = params[:username]
		c.email = params[:email]
		c.content = params[:content]
		c.issue_id = params[:issue_id]
		c.save
		redirect_to c.issue
	end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
  	@issue =Issue.find(params[:id])
    @comments = @issue.comments
  end
  def new
  	@issue = Issue.new
  end
  def destroy
  	i = Issue.find(params[:id])
  	i.destroy
  	redirect_to :root
  end

  def create
    Issue.create(issue_params)
    redirect_to :root
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    i=Issue.find(params[:id]) 
    i.update_attributes(issue_params)
    redirect_to :root
  end

  
  private 
    def issue_params
      params.require(:issue).permit(:title, :content)
    end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController

 	# def new
  # 		@letter = Letter.new
  # 	end
  	def show
  		@letter =Letter.find(params[:id])
  		if (not @letter.is_read || @letter.is_read== false) &&  current_user.name == "丫丫" 
  			@letter.is_read=true
  			@letter.save
  		end
  	    # @comments = @issue.comments
  	end


  	def new
  		@letter =Letter.new
  	end

  	def create
  		Letter.create(letter_params)
  		redirect_to :letterlist
  	end

  	def destroy
  		i = Letter.find(params[:id])
  		i.destroy
  		redirect_to :letterlist
  	end

  	def update
  		i=Letter.find(params[:id]) 
  		i.update_attributes(letter_params)
  		redirect_to :letterlist
  	end


  	def edit
  		@letter = Letter.find(params[:id])
  	end
  	private 
  	def letter_params
  		params.require(:letter).permit!
  	end
  end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def travelnote
		@issues = Issue.all.reverse
		@songs = Song.all
	end

	def music
		@issues = Issue.all.reverse
		@songs = Song.all
	end

	def video
		@issues = Issue.all.reverse
		@songs = Song.all
	end

	def book
		@issues = Issue.all.reverse
		@songs = Song.all
	end

	def digest
		@issues = Issue.all.reverse
		@songs = Song.all
	end


	def image
		@issues = Issue.all.reverse
		@songs = Song.all
	end

	def letter
		@letters=Letter.all.reverse
	end
	
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def show
  	@song =Song.find(params[:id])
    @comments = @song.comments
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      cookies[:auth_token] = @user.auth_token
      redirect_to :root
    else
      render :signup
    end 
  end	

  def login
    
  end

  def logout
    cookies.delete(:auth_token)
    redirect_to :root
  end

  def create_login_session
    
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
        if params[:remember_me]
          cookies.permanent[:auth_token]= user.auth_token
        else
          cookies[:auth_token]=user.auth_token
        end
        flash.notice = "登陆成功!"
        redirect_to :root
    else
      flash.notice ="用户名密码错误!"
      redirect_to :login
    end
  end

  private 
  	def user_params
  		params.require(:user).permit!
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/_form.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for issue do |f| %>
      <dl class="form">
        <dt><%= f.label :歌名 %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :链接 %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/edit.html.erb
<%= render partial: 'form', locals: {issue: @issue} %>

app/views/issues/new.html.erb
<%= render partial: 'form', locals: {issue: @issue} %>

app/views/issues/show.html.erb
<div class="issue-heading">
  <div class="container">
    <%= @issue.title %>

    <% if current_user&&current_user.name == "Ocean-藏心"   %>
    <%= link_to 'edit', edit_issue_path(@issue), class: "btn btn-primary" %>
    <%= link_to 'destroy', issue_path(@issue), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="replies">
    <article class="reply clearfix">
      <div class="avatar">
        <img src="http://tp3.sinaimg.cn/2802042662/180/40063868739/1" alt="" class="image-circle">
      </div>
      <div class="body">
        <div class="heading">
          <h5 class="name"><a href="http://weibo.com/oceancx/">Ocean-藏心</a></h5>
        </div>
        <%= @issue.content %>
      </div>
    </article>
    <%= render partial: 'shared/comment_list', locals: {comments: @comments} %>
    <%= render partial: 'shared/comment_box', locals: {issue: @issue} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>丫丫游记</title>
	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] + '-' + params[:action] %>">

  <div class="navbar clearfix">
    <div class="container">
      <a class="navbar-brand" href="/">
        丫丫游记
      </a>
      <ul class="nav left">
        <li><%= link_to  "音乐","/music" %></li>
        <li><%= link_to  "视频","/video" %></li>
        <li><%= link_to  "读书","/book" %></li>
        <li><%= link_to  "文摘","/digest" %></li>
        <li><%= link_to  "图片","/image" %></li>
        <% if current_user&& (current_user.name == "Ocean-藏心" ||current_user.name == "丫丫") %>  
        <li><%= link_to  "信","/letter" %></li>  
        <% end %>
        <li><%= link_to  t("navbar.about"),"/about" %></li>

      </ul>
      <ul class="nav right">
       <% if current_user %>
       <li><%= link_to current_user.name , "#" %></li>
       <li><%= link_to t("navbar.logout"),logout_path ,method: "delete" %></li>
       <% else %>
       <li><%= link_to t("navbar.login") , login_path %></li>
       <li><%= link_to t("navbar.signup"),signup_path %></li>
       <% end %>
     </ul>
   </div>
 </div>
 <% if flash.notice %>
 <div class="notice"><%= flash.notice %></div>
 <% end %>
 <script>
  $('.home-banner').anystretch();
  var hideNotice = function(){
    $(".notice").fadeOut("slow");
  }
  setTimeout(hideNotice, 2000);
</script>     
<%= yield %>



<div class="footer ">
 <div style="text-align:center" class="container ">
  欢迎关注此网站
</div>
</div>
</body>
</html>

app/views/letters/1.html.erb
asdljwle

app/views/letters/edit.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for @letter do |f| %>
      <dl class="form">
        <dt><%= f.label :标题 %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :内容 %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/letters/new.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for @letter do |f| %>
      <dl class="form">
        <dt><%= f.label :标题 %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :内容 %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/letters/show.html.erb
<div class="issue-heading">
  <div class="container">
    <%= @letter.title %>
  </div>
</div>
<% if current_user&& (current_user.name == "Ocean-藏心" ) %>
<div class="write-letter-bt">
<%= link_to '编辑', edit_letter_path(@letter) %>	
</div>

<div class="write-letter-bt">
<%= link_to '删除', letter_path(@letter), method: :delete, data: { confirm: 'Are you sure?' } %>	
</div>
 
<% end %>

<%=  render html: @letter.content.html_safe   %>

   

app/views/page/_issue_list.html.erb
<div class="issue-list">

  <% issues.each do |i| %>

  <article class="issue clearfix">
    <div class="avatar">
      <a href="/happypeter">
        <img src=http://tp3.sinaimg.cn/2802042662/180/40063868739/1 alt="">
      </a>    
    </div>
      <div class="body">
        <h5 class="title">
       <%= link_to i.title, issue_path(i) %>
        </h5>
        <%=  link_to "听听看",i.content ,class: "read-more"%>
        <span class="meta-data">
          <a href="http://weibo.com/oceancx/">Ocean-藏心</a>
          <%= time_ago_in_words(i.created_at) %> 前        
        </span>
      </div>
      <div class="issue-comment-count">
    <i class="fa fa-comments icon-muted"></i>
       <%= link_to i.comments.count, i %>
      </div>

    </article>
    <% end %>
  </div>

app/views/page/_letter_list.html.erb
<% if current_user&& (current_user.name == "Ocean-藏心" ||current_user.name == "丫丫") %>
<div class="issue-list">
  <% letters.each do |axx| %>   
   <article class="issue clearfix">
      <div class="body">
        <h5 class="title">
          <% if (not axx.is_read ||axx.is_read == false )&& current_user.name == "丫丫" %>
            *
          <% end %>
          <%= link_to axx.title,axx %>
        </h5>
      </div>
    </article>
  <% end %>
  </div>
<% end %>

app/views/page/_letter_list1.html.erb
<% letters.each do |i| %>
  <% if current_user&& (current_user.name == "Ocean-藏心" ||current_user.name == "丫丫") %>
    <div class="lc-wrapper">
      
       <a href="#" class="letter-cover">
        <ul class="zipcode-wrapper">
          <li class="zipcode">1</li>
          <li class="zipcode">0</li>
          <li class="zipcode">0</li>
          <li class="zipcode">0</li>
          <li class="zipcode">0</li>
          <li class="zipcode">0</li>
        </ul>
        
    <img src="/images/stamp-5.jpg" alt="" class="lc-img">      
        
      <div class="footer-container">
        <div class="lc-header clearfix">
            藏心
        </div>
        <div class="lc-footer clearfix">
            2015.10.21
        </div>  
      </div>
      </a>  
      
    </div>
    

  <% end %>
    

<% end %>

app/views/page/_song_list.html.erb
<div class="issue-list">
  <% songs.each do |i| %>
  <article class="issue clearfix">
    <div class="avatar">
      <a href="/happypeter">
        <img src=http://tp3.sinaimg.cn/2802042662/180/40063868739/1 alt="">
      </a>    
    </div>
      <div class="body">
        <h5 class="title">
       <%= link_to i.name, i %>
        </h5>
        <%=  link_to "听听看",i ,class: "read-more"%>
        <span class="meta-data">
          <a href="http://weibo.com/oceancx/">Ocean-藏心</a>
          <%= time_ago_in_words(i.created_at) %> 前        
        </span>
      </div>
      <div class="issue-comment-count">
    <i class="fa fa-comments icon-muted"></i>
       <%= link_to "2", i %>
      </div>

    </article>
    <% end %>
  </div>

app/views/page/about.html.erb
<div class="container">
	<div class="wrapper">
	<h1 class="font-decorate">练手之作，让各位见笑了</h1>	
	<p>版本0.1：Copy rail十日谈 只出了个框架</p>
	</div>
	
</div>

app/views/page/book.html.erb
<div class="home-banner" data-stretch="images/book.jpg" >

  <div class="banner-inner container clearfix">
    <h1>图书馆</h1>
    <p class="subheading">只读经典，才不致于浪费纸张</p>
    <div class="home-banner-links">
      <%= link_to "分享新书", "/issues/new", class: "banner-btn btn" %>
    </div>
  </div>
</div>
<div class="issue-list-header">
  <div class="container clearfix">
    <h1 class="issue-list-heading">书籍列表</h1>
  </div>
</div>

<div class="container clearfix">
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>

<div class="container clearfix">
  <%= render partial: 'song_list', locals: { songs: @songs } %>
</div>

<script>
$('.home-banner').anystretch();
</script>

app/views/page/digest.html.erb
<div class="home-banner" data-stretch="images/digest.jpg" >

  <div class="banner-inner container clearfix">
    <h1>阅览室</h1>
    <p class="subheading">大杂烩，一锅端</p>
    <div class="home-banner-links">
      <%= link_to "分享新文摘", "/issues/new", class: "banner-btn btn" %>
    </div>
  </div>
</div>
<div class="issue-list-header">
  <div class="container clearfix">
    <h1 class="issue-list-heading">文摘列表</h1>
  </div>
</div>

<div class="container clearfix">
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>

<div class="container clearfix">
  <%= render partial: 'song_list', locals: { songs: @songs } %>
</div>

<script>
$('.home-banner').anystretch();
</script>

app/views/page/image.html.erb
<div class="home-banner" data-stretch="images/image.jpg" >

  <div class="banner-inner container clearfix">
    <h1>美景如画</h1>
    <p class="subheading">陶醉其中</p>
    <div class="home-banner-links">
      <%= link_to "分享新图片", "/issues/new", class: "banner-btn btn" %>
    </div>
  </div>
</div>
<div class="issue-list-header">
  <div class="container clearfix">
    <h1 class="issue-list-heading">图片列表</h1>
  </div>
</div>

<div class="container clearfix">
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>

<div class="container clearfix">
  <%= render partial: 'song_list', locals: { songs: @songs } %>
</div>

<script>
$('.home-banner').anystretch();
</script>

app/views/page/letter.html.erb
<div class="toolbar-bg"></div>
<% if current_user&& (current_user.name == "Ocean-藏心") %>
<div class="write-letter-bt">
	<%= link_to "写信", "/letters/new"%>
</div>
<% end %>	

<div class="letter-list-container  clearfix">
  <%= render partial: 'letter_list', locals: { letters: @letters } %>
</div>

app/views/page/letter_new.html.erb
<div class="banner-inner container clearfix">
	<%= link_to "写信", "/letters/new", class: "banner-btn btn" %>
</div>


<div class="container clearfix">
  <%= render partial: 'letter_list', locals: { letters: @letters } %>
</div>

app/views/page/music.html.erb
<div class="home-banner" data-stretch="images/music.jpg" >

  <div class="banner-inner container clearfix">
    <h1>音悦台</h1>
    <p class="subheading">好音乐,大家听</p>
    <div class="home-banner-links">
      <%= link_to "分享新音乐", "/issues/new", class: "banner-btn btn" %>
    </div>
  </div>
</div>
<div class="issue-list-header">
  <div class="container clearfix">
    <h1 class="issue-list-heading">音乐列表</h1>
  </div>
</div>

<div class="container clearfix">
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>

<div class="container clearfix">
  <%= render partial: 'song_list', locals: { songs: @songs } %>
</div>

<script>
$('.home-banner').anystretch();
</script>

app/views/page/travelnote.html.erb
<div class="home-banner" data-stretch="images/travelnote.jpg" >

  <div class="banner-inner container clearfix">
    <h1>点滴记录</h1>
    <p class="subheading">眼中不一样的风景</p>
    <div class="home-banner-links">
      <%= link_to "分享新游记", "/issues/new", class: "banner-btn btn" %>
    </div>
  </div>
</div>
<div class="issue-list-header">
  <div class="container clearfix">
    <h1 class="issue-list-heading">游记列表</h1>
  </div>
</div>

<div class="container clearfix">
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>

<div class="container clearfix">
  <%= render partial: 'song_list', locals: { songs: @songs } %>
</div>

<script>
$('.home-banner').anystretch();
</script>

app/views/page/video.html.erb
<div class="home-banner" data-stretch="images/video1.jpg" >

  <div class="banner-inner container clearfix">
    <h1>点播站</h1>
    <p class="subheading">是否考虑做个生活的导演</p>
    <div class="home-banner-links">
      <%= link_to "分享新视频", "/issues/new", class: "banner-btn btn" %>
    </div>
  </div>
</div>
<div class="issue-list-header">
  <div class="container clearfix">
    <h1 class="issue-list-heading">视频列表</h1>
  </div>
</div>

<div class="container clearfix">
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>

<div class="container clearfix">
  <%= render partial: 'song_list', locals: { songs: @songs } %>
</div>

<script>
$('.home-banner').anystretch();
</script>

app/views/shared/_comment_box.html.erb
<article class="reply clearfix">
  <div class="avatar">
    <%= link_to "#" do %>
    <%= image_tag "default_avatar.png", class: "image-circle" %>
    <% end %>
  </div>
  <div class="body">

   <%= form_tag("/issues/#{issue.id}/comments", method: :post) do  %>
     <%= label_tag :username, "用户名" %>
     <%= text_field_tag(:username) %>
     <%= label_tag :email, "邮箱" %>
     <%= text_field_tag(:email) %>
     <%= label_tag :content,"" %>
     <%= text_area_tag(:content) %>
     <%= submit_tag '提交评论', class: 'btn btn-primary btn-submit' %>
     <% end %> 

 </div>
</article>

app/views/shared/_comment_list.html.erb
<% comments.each do |c| %>
    <div class="reply clearfix">
       <div class="avatar">
         <%= link_to '#' do %>
           <%= image_tag c.user_avatar, class: 'image-circle' %>
         <% end %>
       </div>
       <div class="body">
         <div class="heading">
            <h5 class="name"><%= link_to c.username, "#" %></h5>
            <span class="datetime">
              <%= time_ago_in_words c.created_at %> 前
            </span>
         </div>
         <%= c.content %>
       </div>
    </div>
  <% end %>

app/views/users/login.html.erb
<div class="login-form-container clearfix">
  <div class="login-form">
    <%= form_tag "/create_login_session" do %>
    <dl class="form">
      <dt>
        <%= label_tag "用户名" %>
      </dt>
      <dd>
        <%= text_field_tag :name, params[:name] %>
      </dd>
    </dl>
    <dl class="form">
      <dt>
        <%= label_tag "密码" %>
      </dt>
      <dd>
        <%= password_field_tag :password, params[:password] %>
      </dd>
    </dl>
    <dl class="form remember-me">
      <%= check_box_tag :remember_me, 1, params[:remember_me] %>
      <%= label_tag :remember_me %>
    </dl>
    <p> <%= submit_tag "登录", :class => "login-button btn btn-primary" %> </p>
    <div class="need-signup">
      <%= link_to "没有账号？注册一个吧", signup_path %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/signup.html.erb
<div class="signup-form-container clearfix">
  <div class="signup-form">
    <%= form_for @user do |f| %>
    <dl class="form">
      <dt><%= f.label :name, "用户名" %></dt>
      <dd><%= f.text_field :name %></dd>
      <% if @user.errors[:name].any? %>
      <dd class="error"><%= @user.errors[:name][0] %></dd>
      <% end %>
    </dl>
    <dl class="form">
      <dt><%= f.label :email %></dt>
      <dd><%= f.text_field :email %></dd>
      <% if @user.errors[:email].any? %>
      <dd class="error"><%= @user.errors[:email][0] %></dd>
      <% end %>
    </dl>
    <dl class="form">
      <dt><%= f.label :password, "密码" %></dt>
      <dd><%= f.password_field :password %></dd>
      <% if @user.errors[:password].any? %>
      <dd class="error"><%= @user.errors[:password][0] %></dd>
      <% end %>
    </dl>
    <dl class="form">
      <dt><%= f.label :password_confirmation, "请再输入一次" %></dt>
      <dd><%= f.password_field :password_confirmation %></dd>
      <% if @user.errors[:password_confirmation].any? %>
      <dd class="error"><%= @user.errors[:password_confirmation][0] %></dd>
      <% end %>
    </dl>
    <p><%= f.submit "注册", :class => "signup-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>